### ISSUE TITLE
Unrecognized field "channel"

### ISSUE THREAD

**Issue by viveleroi** [jpenilla/run-paper#10]
I'm suddenly getting this error in any of my projects that use this plugin. I've tried using different java versions too.

Version 1.0.1-SNAPSHOT

`Unrecognized field "channel" (class xyz.jpenilla.runpaper.paperapi.BuildResponse), not marked as ignorable (7 known properties: "project_id", "changes", "version", "downloads", "time", "build", "project_name"])
 at [Source: UNKNOWN; line: 1, column: 420] (through reference chain: xyz.jpenilla.runpaper.paperapi.BuildResponse["channel"])`

**Comment by jpenilla** [comment]
https://github.com/jpenilla/run-paper/releases/tag/v1.0.6
