### ISSUE TITLE
Feature request: Run Minecraft Server based off of Project SDK version rather than user's JAVA_HOME

### ISSUE THREAD

**Issue by AshIndigo** [jpenilla/run-paper#12]
Would make it easier to develop for different Minecraft versions since I admittedly just spent one too many minutes trying to figure out why my 1.17.1 server wasn't launching with this before I realized my JAVA_HOME was set to java 17. And it wasn't using my Java 16 which I had set my project SDK to

**Comment by jpenilla** [comment]
if you configure the java toolchain, run paper will use it by default. additionally most old minecraft versions can run fine on jdk 17 if you provide the paper flag `systemProperty("Paper.IgnoreJavaVersion", true)`
