### ISSUE TITLE
Allow for adding launch arguments

### ISSUE THREAD

**Issue by u9g** [jpenilla/run-paper#18]
I'd like to be able to add an argument to the command that runs the server so I can build my plugin with this: https://github.com/Paul19988/Advanced-Slime-World-Manager/blob/1.18/.docs/usage/install.md#how-to-install-swm

**Comment by jpenilla** [comment]
`RunServerTask` extends [JavaExec](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/JavaExec.html), so the APIs exposed there for modifying args/jvmArgs will work fine.
