### ISSUE TITLE
Skip looking up new build for x amount of time

### ISSUE THREAD

**Issue by PaulBGD** [jpenilla/run-paper#2]
Besides having faster server startup, for those of us with slow internet just checking for a new build can take an extra second or two (or timeout.) It'd be great if it only checked for a new Paper build every 24 hours, with possibly an option for force checking.

**Comment by jpenilla** [comment]
Implemented in ccc8f55/`1.0.2-SNAPSHOT` on my repo.

As documented here: https://docs.gradle.org/current/userguide/build_environment.html, properties are resolved such that a value set in `GRADLE_USER_HOME/gradle.properties` will take precedence over a value set in the project `gradle.properties`, which allows for those with slow internet to set an override for their system.

See here for the format for this property until I document it in the wiki: https://github.com/jpenilla/run-paper/blob/master/src/main/kotlin/xyz/jpenilla/runpaper/util/DurationParser.kt#L33-L42

**Comment by PaulBGD** [comment]
Looks great, thanks!

**Comment by jpenilla** [comment]
[1.0.2](https://plugins.gradle.org/plugin/xyz.jpenilla.run-paper/1.0.2) has been released.
