### ISSUE TITLE
How to add eula flag

### ISSUE THREAD

**Issue by josephjthomas** [jpenilla/run-paper#22]
How can I parse `-Dcom.mojang.eula.agree=true` as flag if I invoke `runServer`? Can I add flags at all, like Aikar's flags for example.

**Comment by jpenilla** [comment]
duplicate #18

**Comment by josephjthomas** [comment]
> duplicate #18

Could you show me an example how I can add it to my runServer task?
```kt
tasks {
  runServer {
    minecraftVersion("1.19")
  }
}
```
Thanks.

**Comment by AlexTMjugador** [comment]
This issue has pretty good SEO idnexing, so I figured I could share an example on how to set the requested flag:
```
tasks {
  runServer {
    minecraftVersion("1.19")
    jvmArgs("-Dcom.mojang.eula.agree=true")
  }
}
```
