### ISSUE TITLE
Support multiple run server configurations

### ISSUE THREAD

**Issue by DevSrSouza** [jpenilla/run-paper#7]
The proposal is something similar to `maven-publish` that you could have a bunch of different tasks for multiple servers setups.

This allows Monorepo projects for a big network project to setup different types of servers, plugins, modules and configurations.

**Comment by jpenilla** [comment]
This should already be possible by configuring your own `RunServerTask`s, can see a basic example [here](https://github.com/Incendo/cloud/blob/d55f59b227af0dd242e59c9993a787895485733b/examples/example-bukkit/build.gradle.kts#L37-L60).

The main thing to note when doing this is that you'll need to add plugin jars to the `pluginJars` `ConfigurableFileCollection` [yourself](https://github.com/Incendo/cloud/blob/d55f59b227af0dd242e59c9993a787895485733b/examples/example-bukkit/build.gradle.kts#L54), as `run-paper` won't know about tasks you register on your own.

**Comment by DevSrSouza** [comment]
@jpenilla there is any special function built in the `run-paper` that you use the get the `pluginJars` your self that you could expose it publicly?

**Comment by jpenilla** [comment]
Nothing special really, it just checks for `shadowJar` and then `jar` in that order, and if one is found it's added to `pluginJars`.

See https://github.com/jpenilla/run-paper/blob/db26283992da89a3486d8edd7c325ca53e1196fe/src/main/kotlin/xyz/jpenilla/runpaper/task/RunServerTask.kt#L323-L328 and https://github.com/jpenilla/run-paper/blob/db26283992da89a3486d8edd7c325ca53e1196fe/src/main/kotlin/xyz/jpenilla/runpaper/RunPaper.kt#L44-L54

I don't think `resolvePluginJarTask` is something I would like to expose to the API as it's an implementation detail which can change, and does change in the open PR for paperweight-userdev integration.

**Comment by DevSrSouza** [comment]
That make sense, thanks :D
