### ISSUE TITLE
Support or new plugin for purpur?

### ISSUE THREAD

**Issue by viveleroi** [jpenilla/run-paper#8]
I've been using for paper and love it, but one of my plugins likely needs to use purpur. I would love a similar plugin like this for gradle and purpur. I don't know what would be involved but it makes plugin dev much easier. Since purpur is a paper fork and they have a download API as well, I assume it's not terribly different but am unsure.

**Comment by jpenilla** [comment]
In 1.0.4 you'll be able to specify a custom jar to run the server from using the [`serverJar`](https://github.com/jpenilla/run-paper/blob/master/src/main/kotlin/xyz/jpenilla/runpaper/task/RunServerTask.kt#L68) property, which you can set to a purpur jar.

(This can already be done by setting the `paperclipJar` property, however I recently [renamed](https://github.com/jpenilla/run-paper/commit/c96548af33c9af720d4bffd258c58edbe6dee3cc) the property for clarity)

As far as automated downloads for purpur, If purpur used the [Paper downloads API v2](https://github.com/PaperMC/bibliothek), I may consider adding support, however as is they use a non-standard downloads API and I have no interest in supporting it.

**Comment by TMUniversal** [comment]
Purpur allows downloads via their v2 API, although I'm not sure that it's the Paper API:
```
https://api.purpurmc.org/v2/purpur/1.19.2/latest/download
```
or
```
https://api.purpurmc.org/v2/purpur/<minecraft version>/<build number>/download
```

If you don't want to add support for this directly,
would you add documentation explaining how to add a Gradle provider to download the file for us?
